const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const esbuild = require('esbuild');
function load(file, uni = {}, pages = () => []) {
  const code = esbuild.buildSync({ entryPoints: [file], bundle: true, write: false, platform: 'node', format: 'cjs', logLevel: 'silent' }).outputFiles[0].text;
  const module = { exports: {} };
  new Function('module', 'exports', 'require', 'uni', 'getCurrentPages', code)(module, module.exports, require, uni, pages);
  return module.exports;
}
const m = load('src/mall/model.ts');
const p = load('src/mall/product-selection.ts');
const f = load('src/mall/fixtures.ts');
const now = new Date('2026-09-18T10:00:00Z');
const selection = (changes = {}) => ({ productId: '1', name: '测试商品', cover: '/static/mall/passport.png', categoryId: 1, specKey: 'standard', specName: '标准办理', group: '成人', date: '2026-10-12', unitCents: 69900, quantity: 1, stock: 20, travellersRequired: true, shippingRequired: false, ...changes });
const people = count => Array.from({ length: count }, (_, i) => ({ name: '测试出行人' + i, passport: 'ETEST000' + i, birthday: '1990-01-01' }));
function member() { const state = m.createState(); state.member = true; return state; }
function ready(state, changes = {}) {
  const line = m.makeLine(selection(changes));
  m.beginCheckout(state, [line], 'buy'); state.draft.consent = true;
  if (line.travellersRequired) m.saveTravellers(state, line.id, people(line.quantity));
  return line;
}
test('默认是游客，不创建真实订单', () => { const s = m.createState(); assert.equal(s.member, false); assert.equal(s.orders.length, 0); assert.throws(() => m.submitOrder(s, now), /登录/); });
test('明细 ID 区分商品、套餐、人群和日期', () => { const base = selection(); const ids = [base, selection({ specKey: 'fast' }), selection({ group: '儿童' }), selection({ date: '2026-10-13' }), selection({ productId: '2' })].map(m.lineId); assert.equal(new Set(ids).size, 5); });
test('相同规格合并购物车，不丢商品身份', () => { const s = m.createState(); m.addToCart(s, selection()); m.addToCart(s, selection({ quantity: 2 })); assert.equal(s.cart.length, 1); assert.equal(s.cart[0].quantity, 3); });
test('数量、库存与价格输入受校验', () => { for (const value of [0, -1, 1.5, 21, NaN]) assert.throws(() => m.makeLine(selection({ quantity: value }))); assert.throws(() => m.makeLine(selection({ unitCents: -1 }))); assert.throws(() => m.makeLine(selection({ date: '2026-02-30' }))); });
test('购物车排序不改变出行人归属', () => { const s = member(); const a = m.makeLine(selection()), b = m.makeLine(selection({ date: '2026-10-13' })); m.beginCheckout(s, [a, b], 'cart'); m.saveTravellers(s, a.id, people(1)); m.beginCheckout(s, [b, a], 'cart'); assert.equal(s.draft.lines[1].travellers[0].name, '测试出行人0'); assert.equal(s.draft.lines[0].travellers.length, 0); });
test('增加人数必须补齐，减少人数保留对应前序名单', () => { const s = member(); ready(s); m.beginCheckout(s, [m.makeLine(selection({ quantity: 2 }))], 'buy'); assert.match(m.validateTravellers(s.draft.lines[0]), /2 位/); m.saveTravellers(s, s.draft.lines[0].id, people(2)); m.beginCheckout(s, [m.makeLine(selection())], 'buy'); assert.equal(s.draft.lines[0].travellers.length, 1); });
test('同一商品护照重复与未来生日不能提交', () => { const line = m.makeLine(selection({ quantity: 2 })); const list = people(2); list[1].passport = list[0].passport; assert.match(m.validateTravellers(line, list, '2026-09-18'), /重复/); list[1].passport = 'EOTHER001'; list[1].birthday = '2099-01-01'; assert.match(m.validateTravellers(line, list, '2026-09-18'), /生日/); });
test('不需要出行人的商品不强制填写', () => { const s = member(); ready(s, { travellersRequired: false }); assert.equal(m.submitOrder(s, now).lines[0].travellers.length, 0); });
test('未勾选预订确认不能提交', () => { const s = member(); ready(s); s.draft.consent = false; assert.throws(() => m.submitOrder(s, now), /勾选/); });
test('需要邮寄的商品必须选地址', () => { const s = member(); ready(s, { shippingRequired: true }); assert.throws(() => m.submitOrder(s, now), /地址/); });
test('选券同时校验类别、门槛、日期及占用', () => { const s = member(), coupon = s.coupons.find(c => c.id === 'visa'); assert.match(m.couponIssue(coupon, [m.makeLine(selection({ categoryId: 2 }))], '2026-09-18'), /不适用/); assert.match(m.couponIssue(coupon, [m.makeLine(selection())], '2026-09-18'), /门槛/); assert.equal(m.couponIssue(coupon, [m.makeLine(selection({ quantity: 2 }))], '2026-09-18'), ''); assert.match(m.couponIssue(coupon, [m.makeLine(selection({ quantity: 2 }))], '2027-01-01'), /过期/); coupon.reservedBy = 'other'; assert.match(m.couponIssue(coupon, [m.makeLine(selection({ quantity: 2 }))], '2026-09-18'), /占用/); });
test('计价使用分，叠加顺序一致且结果不为负', () => { const s = member(); const price = m.quote([m.makeLine(selection({ quantity: 2 }))], s.coupons.find(c => c.id === 'visa'), true, 1280, '2026-09-18'); assert.deepEqual(price, { base: 139800, groupDiscount: 13980, coupon: 5000, points: 1280, pointsCents: 2560, due: 118260 }); assert.equal(m.quote([m.makeLine(selection({ unitCents: 1 }))], undefined, true, 100000).due >= 0, true); });
test('重复提交同一草稿不重复扣积分或占券', () => { const s = member(); ready(s, { quantity: 2 }); s.draft.usePoints = true; s.draft.couponId = 'visa'; const first = m.submitOrder(s, now), balance = s.balance; const second = m.submitOrder(s, now); assert.equal(first.id, second.id); assert.equal(s.orders.length, 1); assert.equal(s.balance, balance); assert.equal(s.coupons.find(c => c.id === 'visa').reservedBy, first.id); });
test('订单快照独立于后续草稿和地址编辑', () => { const s = member(); ready(s, { shippingRequired: true }); const address = m.saveAddress(s, { id: '', name: '测试', phone: '13800000000', region: ['广东省', '广州市', '天河区'], detail: '测试路1号', isDefault: true }); s.draft.addressId = address.id; const order = m.submitOrder(s, now); s.draft.lines[0].name = '已改'; address.detail = '已改'; assert.equal(order.lines[0].name, '测试商品'); assert.equal(order.address.detail, '测试路1号'); });
test('支付失败及取消仍为待付款，重试成功进入办理中', () => { const s = member(); ready(s); const order = m.submitOrder(s, now); m.payment(s, order.id, 'failed'); assert.equal(order.status, '待付款'); m.payment(s, order.id, 'cancelled'); assert.equal(order.status, '待付款'); m.payment(s, order.id, 'succeeded'); assert.equal(order.status, '办理中'); m.payment(s, order.id, 'succeeded'); assert.equal(s.orders.length, 1); });
test('取消订单只返还一次积分并释放优惠券', () => { const s = member(); ready(s, { quantity: 2 }); s.draft.usePoints = true; s.draft.couponId = 'visa'; const balance = s.balance, order = m.submitOrder(s, now); m.cancelOrder(s, order.id); m.cancelOrder(s, order.id); assert.equal(s.balance, balance); assert.equal(s.coupons.find(c => c.id === 'visa').reservedBy, undefined); assert.throws(() => m.payment(s, order.id, 'succeeded'), /不可付款/); });
test('退款申请只进入审核中，不提前返还积分或券', () => { const s = member(); ready(s); s.draft.usePoints = true; const order = m.submitOrder(s, now); m.payment(s, order.id, 'succeeded'); const balance = s.balance; m.requestRefund(s, order.id, '出行计划变更', '测试', now); assert.equal(order.status, '售后退款'); assert.equal(s.balance, balance); assert.throws(() => m.requestRefund(s, order.id, '其他', '', now), /不可申请/); });
test('超期退款在暂定演示口径下被拦截', () => { const s = member(); ready(s); const order = m.submitOrder(s, now); m.payment(s, order.id, 'succeeded'); assert.throws(() => m.requestRefund(s, order.id, '其他', '', new Date('2027-04-18')), /半年/); });
test('地址 CRUD 保持唯一默认地址并清理失效选择', () => { const s = member(); const data = { id: '', name: '测试', phone: '13800000000', region: ['广东省', '广州市', '天河区'], detail: '测试路1号', isDefault: false }; const a = m.saveAddress(s, data); const b = m.saveAddress(s, { ...data, isDefault: true }); assert.equal(s.addresses.filter(x => x.isDefault).length, 1); assert.equal(a.isDefault, false); ready(s); s.draft.addressId = b.id; m.deleteAddress(s, b.id); assert.equal(a.isDefault, true); assert.equal(s.draft.addressId, ''); });
test('退出清除所有私人数据但保留商品选择', () => { const s = member(); m.addToCart(s, selection()); ready(s); m.signOut(s); assert.equal(s.member, false); assert.equal(s.orders.length, 0); assert.equal(s.addresses.length, 0); assert.equal(s.cart.length, 1); assert.equal(s.draft.lines[0].travellers.length, 0); });
test('日历选价使用既有分单位且拒绝无名额日期', () => { const goods = f.demoGoods()[0], spec = goods.specification[0]; const slot = p.calendarSlots(spec, spec.person[0])[0]; const selected = p.selectionFor(goods, spec, spec.person[0], slot.date, 1); assert.equal(selected.unitCents, goods.price); assert.throws(() => p.selectionFor(goods, spec, spec.person[0], '1900-01-01', 1), /日历/); });
test('登录返回 Tab 与已有非 Tab 页面实例正确', () => { const calls = []; let stack = []; const uni = Object.fromEntries(['switchTab', 'redirectTo', 'navigateBack', 'reLaunch'].map(name => [name, opts => calls.push([name, opts])])); const routes = load('src/utils/auth-routing.ts', uni, () => stack); routes.returnFromLogin('/pages/account/index'); assert.equal(calls.pop()[0], 'switchTab'); stack = [{ route: 'pagesMall/orders/index', options: { filter: '办理中' } }, { route: 'pages/login/index' }]; routes.returnFromLogin('/pagesMall/orders/index?filter=' + encodeURIComponent('办理中')); assert.equal(calls.pop()[0], 'navigateBack'); });
test('所有商城路由均注册，只有三个原生 Tab', () => { const config = JSON.parse(fs.readFileSync('src/pages.json', 'utf8')); const all = [...config.pages.map(p => p.path), ...config.subPackages.flatMap(pack => pack.pages.map(p => pack.root + '/' + p.path))]; const routes = load('src/mall/navigation.ts').routes; for (const route of Object.values(routes)) assert.ok(all.includes(route.slice(1)), route); for (const file of all) assert.ok(fs.existsSync('src/' + file + '.vue'), file); assert.deepEqual(config.tabBar.list.map(p => p.text), ['首页', '产品分类', '我的']); });
test('改动中的 Vue 单文件脚本和模板均可编译', () => { const compiler = require('@vue/compiler-sfc'); const files = execFileSync('git', ['diff', '--name-only', 'cb25781561fda5424a75b591bcccadfbb8e8e477', 'HEAD', '--', '*.vue'], { encoding: 'utf8' }).trim().split('\n').filter(Boolean); assert.ok(files.length > 20); for (const file of files) { const parsed = compiler.parse(fs.readFileSync(file, 'utf8'), { filename: file }); assert.equal(parsed.errors.length, 0, file); const descriptor = parsed.descriptor; const script = descriptor.scriptSetup ? compiler.compileScript(descriptor, { id: file }) : null; if (descriptor.template) { const output = compiler.compileTemplate({ source: descriptor.template.content, filename: file, id: file, compilerOptions: { bindingMetadata: script?.bindings, expressionPlugins: ['typescript'] } }); assert.equal(output.errors.length, 0, file + ': ' + output.errors.join('\n')); } } });
test('演示领域及新业务页面没有支付调用或私人持久化', () => { const files = execFileSync('git', ['diff', '--name-only', 'cb25781561fda5424a75b591bcccadfbb8e8e477', 'HEAD', '--', 'src/pagesMall', 'src/mall', 'src/store/mall-preview.ts'], { encoding: 'utf8' }).trim().split('\n').filter(x => /\.(vue|ts)$/.test(x)); for (const file of files) { const source = fs.readFileSync(file, 'utf8'); assert.doesNotMatch(source, /uni\.requestPayment\s*\(|uni\.setStorage(?:Sync)?\s*\(|localStorage\./, file); } });
test('预览开关默认关闭，预览启动与正式会话隔离', () => { const config = fs.readFileSync('src/mall/config.ts', 'utf8'); assert.match(config, /VITE_MALL_PREVIEW\s*===\s*'true'/); const app = fs.readFileSync('src/App.vue', 'utf8'); assert.match(app, /if \(!MALL_PREVIEW\) void global\.initialize/); assert.match(app, /!MALL_PREVIEW && global\.status/); });
